This dataset comes from the [Cal Fires website](http://frap.fire.ca.gov/data/frapgisdata-sw-fireperimeters_download). Data from 1878-2017 is available. Information on table attributes can be found [here](http://frap.fire.ca.gov/projects/fire_data/fire_perimeters_data_description), while information about data collection can be found [here](http://frap.fire.ca.gov/projects/fire_data/fire_perimeters_index). 

# Plan 

-- trend of causes... have human-caused ones increased? 

-- wildfire season longer? See how many big ones happen per month

-- wildfires occur more in general? See how many occur per year

-- look at counties... does one area have more than others? 

-- potentially see how biodiversity is affected

-- timeseries months&year trend: https://plot.ly/python/time-series/

In [12]:
import numpy as np
import pandas as pd
import plotly.plotly as py
#import to run offline 
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [15]:
#call to run offline
init_notebook_mode(connected=True)

In [17]:
df17 = pd.read_csv('~/URAP/cal_fires/data/calfires17.csv')
dfPast = pd.read_csv('~/URAP/cal_fires/data/calfires1878_2016.csv')
#rename the "YEAR_" column in dfFires so that we can append the past fires to it and have the "YEAR" 
#columns match up 
df17.rename(columns={'YEAR_': 'YEAR'}, inplace=True)

In [94]:
#past_fires.where(isinstance("YEAR", int)).sort("YEAR", descending = True)
#we see null and nan values in this table! 


In [18]:
#merge these tables together 
total_fires = df17.append(dfPast)
total_fires.head()
##fires = Table.from_df(total_fires)
##fires.sort('YEAR', descending=True)
#sort to see that we still need to clean data

#tbl_total_fires=Table.from_df(total_fires)
#tbl_total_fires.sort('YEAR', descending=True)

YEAR       STATE                                             AGENCY  \
0  2017  California  California Department of Forestry and Fire Pro...   
1  2017  California  California Department of Forestry and Fire Pro...   
2  2017  California  California Department of Forestry and Fire Pro...   
3  2017  California  California Department of Forestry and Fire Pro...   
4  2017  California  California Department of Forestry and Fire Pro...   

                         UNIT_ID     FIRE_NAME INC_NUM  ALARM_DATE  \
0                  Tulare County        DINELY     286    6/7/2017   
1                  Tulare County    ROADRUNNER     441   7/30/2017   
2                  Tulare County    ELEPHANT 2     420   7/20/2017   
3        Tehama - Glenn CAL FIRE        TEHAMA   10345  10/30/2017   
4  Tuolumne - Calaveras CAL FIRE  JACKSONVILLE    9024   7/29/2017   

    CONT_DATE                        CAUSE COMMENTS REPORT_AC  GIS_ACRES  \
0   6/11/2017            2 - Equipment Use   <Null>       339   340.5638   
1    8/1/2017                    7 - Arson   <Null>      2289  2284.5960   
2   7/22/2017                    7 - Arson   <Null>       416   415.2116   
3  10/31/2017                 10 - Vehicle   <Null>       194   194.0017   
4   7/30/2017  14 - Unknown / Unidentified   <Null>    <Null>   684.3565   

         C_METHOD               OBJECTIVE  
0  1 - GPS Ground  Suppression (Wildfire)  
1  1 - GPS Ground  Suppression (Wildfire)  
2  1 - GPS Ground  Suppression (Wildfire)  
3  1 - GPS Ground  Suppression (Wildfire)  
4  1 - GPS Ground  Suppression (Wildfire)

In [19]:
total_fires['YEAR'].unique()
#there are null and nans in our data! Get rid of these from the YEAR column 

array([2017, 2018, '1878', '1895', '1896', '1898', '1900', '1902', '1903',
       '1905', '1906', '1907', '1908', '1909', '1910', '1911', '1912',
       '1913', '1914', '1915', '1916', '1917', '1918', '1919', '1920',
       '1921', '1922', '1923', '1924', '1925', '1926', '1927', '1928',
       '1929', '1930', '1931', '1932', '1933', '1934', '1935', '1936',
       '1937', '1938', '1939', '1940', '1941', '1942', '1943', '1944',
       '1945', '1946', '1947', '1948', '1949', '1950', '1951', '1952',
       '1953', '1954', '1955', '1956', '1957', '1958', '1959', '1960',
       '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976',
       '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
  

In [20]:
#get rid of null values in YEAR column 
no_nulls = total_fires[total_fires["YEAR"] != "<Null>"]
x = no_nulls["YEAR"].unique()[-1]
#get rid of nan
no_nulls = no_nulls[no_nulls["YEAR"].notna()]
no_nulls.head()

YEAR       STATE                                             AGENCY  \
0  2017  California  California Department of Forestry and Fire Pro...   
1  2017  California  California Department of Forestry and Fire Pro...   
2  2017  California  California Department of Forestry and Fire Pro...   
3  2017  California  California Department of Forestry and Fire Pro...   
4  2017  California  California Department of Forestry and Fire Pro...   

                         UNIT_ID     FIRE_NAME INC_NUM  ALARM_DATE  \
0                  Tulare County        DINELY     286    6/7/2017   
1                  Tulare County    ROADRUNNER     441   7/30/2017   
2                  Tulare County    ELEPHANT 2     420   7/20/2017   
3        Tehama - Glenn CAL FIRE        TEHAMA   10345  10/30/2017   
4  Tuolumne - Calaveras CAL FIRE  JACKSONVILLE    9024   7/29/2017   

    CONT_DATE                        CAUSE COMMENTS REPORT_AC  GIS_ACRES  \
0   6/11/2017            2 - Equipment Use   <Null>       339   340.5638   
1    8/1/2017                    7 - Arson   <Null>      2289  2284.5960   
2   7/22/2017                    7 - Arson   <Null>       416   415.2116   
3  10/31/2017                 10 - Vehicle   <Null>       194   194.0017   
4   7/30/2017  14 - Unknown / Unidentified   <Null>    <Null>   684.3565   

         C_METHOD               OBJECTIVE  
0  1 - GPS Ground  Suppression (Wildfire)  
1  1 - GPS Ground  Suppression (Wildfire)  
2  1 - GPS Ground  Suppression (Wildfire)  
3  1 - GPS Ground  Suppression (Wildfire)  
4  1 - GPS Ground  Suppression (Wildfire)

In [21]:
no_nulls.columns.values

array(['YEAR', 'STATE', 'AGENCY', 'UNIT_ID', 'FIRE_NAME', 'INC_NUM',
       'ALARM_DATE', 'CONT_DATE', 'CAUSE', 'COMMENTS', 'REPORT_AC',
       'GIS_ACRES', 'C_METHOD', 'OBJECTIVE'], dtype=object)

In [22]:
dfFilteredColumns = no_nulls[['YEAR', 'STATE','UNIT_ID', 'FIRE_NAME', 
       'ALARM_DATE', 'CAUSE','GIS_ACRES']]
dfFilteredColumns.head()

YEAR       STATE                        UNIT_ID     FIRE_NAME  ALARM_DATE  \
0  2017  California                  Tulare County        DINELY    6/7/2017   
1  2017  California                  Tulare County    ROADRUNNER   7/30/2017   
2  2017  California                  Tulare County    ELEPHANT 2   7/20/2017   
3  2017  California        Tehama - Glenn CAL FIRE        TEHAMA  10/30/2017   
4  2017  California  Tuolumne - Calaveras CAL FIRE  JACKSONVILLE   7/29/2017   

                         CAUSE  GIS_ACRES  
0            2 - Equipment Use   340.5638  
1                    7 - Arson  2284.5960  
2                    7 - Arson   415.2116  
3                 10 - Vehicle   194.0017  
4  14 - Unknown / Unidentified   684.3565

In [40]:
#get rid of unidentified causes 
dfFiltered = dfFilteredColumns[dfFilteredColumns["CAUSE"] != "14 - Unknown / Unidentified"]
dfFiltered.head()

YEAR       STATE                        UNIT_ID   FIRE_NAME  ALARM_DATE  \
0  2017  California                  Tulare County      DINELY    6/7/2017   
1  2017  California                  Tulare County  ROADRUNNER   7/30/2017   
2  2017  California                  Tulare County  ELEPHANT 2   7/20/2017   
3  2017  California        Tehama - Glenn CAL FIRE      TEHAMA  10/30/2017   
7  2017  California  Tuolumne - Calaveras CAL FIRE       POINT   10/9/2017   

               CAUSE  GIS_ACRES  
0  2 - Equipment Use   340.5638  
1          7 - Arson  2284.5960  
2          7 - Arson   415.2116  
3       10 - Vehicle   194.0017  
7     11 - Powerline   130.2357

In [41]:
#double check type of YEAR
dfFiltered['YEAR'].dtype

dtype('O')

In [101]:
#trend of human-caused fires throughout the years 
#get rid of unknown/unidentified 
#get rid of comments 
#map of where they're most prevalent/ get counts 
#cut table from 1950 - now??? 



In [51]:
#convert YEAR strings to integers to make this column easier to work with
#UM WHY DID THIS WORK FOR LIKE 2 SECONDS

#pd.to_numeric(dfFiltered['YEAR'], errors='coerce', downcast = 'integer').head()
#pd.to_numeric(dfFiltered['YEAR'], errors='coerce').head()
#dfFiltered['YEAR'].astype(str).astype(int).head()
#dfFiltered['YEAR'].astype(np.int64).head() 

#OK I GUESS THIS WORKS???
dfFiltered['YEAR'].apply(lambda x: int(x))
dfFiltered['YEAR'].unique()

array([2017, 2018, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918,
       1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929,
       1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940,
       1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951,
       1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962,
       1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973,
       1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
       1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      dtype=int64)

In [53]:
#cut our data so we can look at 1950-2017
dfFiltered = dfFiltered[dfFiltered['YEAR'] > 1950]
dfFiltered['YEAR'].unique()

array([2017, 2018, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959,
       1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016], dtype=int64)

In [54]:
#rename this dataframe 
fires = dfFiltered
fires.head()

YEAR       STATE                        UNIT_ID   FIRE_NAME  ALARM_DATE  \
0  2017  California                  Tulare County      DINELY    6/7/2017   
1  2017  California                  Tulare County  ROADRUNNER   7/30/2017   
2  2017  California                  Tulare County  ELEPHANT 2   7/20/2017   
3  2017  California        Tehama - Glenn CAL FIRE      TEHAMA  10/30/2017   
7  2017  California  Tuolumne - Calaveras CAL FIRE       POINT   10/9/2017   

               CAUSE  GIS_ACRES  
0  2 - Equipment Use   340.5638  
1          7 - Arson  2284.5960  
2          7 - Arson   415.2116  
3       10 - Vehicle   194.0017  
7     11 - Powerline   130.2357

In [55]:
#list of fire frequency per location 
#make bubble map w/ this?? 
fires['UNIT_ID'].value_counts().head()

Sequoia National Forest           241
Cleveland National Forest         237
Riverside CAL FIRE                203
San Diego CAL FIRE                169
Shasta-Trinity National Forest    166
Name: UNIT_ID, dtype: int64

In [57]:
fires['CAUSE'].value_counts()

1 - Lightning                    1302
9 - Miscellaneous                 961
2 - Equipment Use                 523
7 - Arson                         458
4 - Campfire                      172
5 - Debris                        168
10 - Vehicle                      164
11 - Powerline                    140
3 - Smoking                       114
8 - Playing with fire              76
18 - Escaped Prescribed Burn       40
6 - Railroad                       31
<Null>                             11
15 - Structure                      8
13 - Non-Firefighter Training       7
16 - Aircraft                       7
19 - Illegal Alien Campfire         4
12 - Firefighter Training           4
Name: CAUSE, dtype: int64

In [64]:
fires = fires[(fires["CAUSE"] != "<Null>") & (fires["CAUSE"] != "9 - Miscellaneous") 
             & (fires["CAUSE"] != "18 - Escaped Prescribed Burn")
             & (fires["CAUSE"] != "12 - Firefighter Training")
             & (fires["CAUSE"] != "13 - Non-Firefighter Training")]

fires['CAUSE'].value_counts()

1 - Lightning                  1302
2 - Equipment Use               523
7 - Arson                       458
4 - Campfire                    172
5 - Debris                      168
10 - Vehicle                    164
11 - Powerline                  140
3 - Smoking                     114
8 - Playing with fire            76
6 - Railroad                     31
15 - Structure                    8
16 - Aircraft                     7
19 - Illegal Alien Campfire       4
Name: CAUSE, dtype: int64

In [65]:
#somehow pivot city and causes to see if there are any patterns in causes and location? 

### Look at trend of arson to create simple line graph 

In [94]:
fires_arson = fires[['YEAR', 'CAUSE']]
fires_arson = fires_arson[fires_arson["CAUSE"] == "7 - Arson"]
#fires_arson['YEAR'].value_counts() #.sort_values('YEAR')
#group by year, see counts for number of arson incidents per year
fires_arson.groupby(['YEAR']).agg(['count']).head()

CAUSE
     count
YEAR      
1957     1
1961     1
1966     1
1967     1
1968     2

In [95]:

arson_x = fires_arson['YEAR']
arson_y = fires_arson['CAUSE']

trace = go.Scatter(
    x = arson_x,
    y = arson_y
)

data = [trace]

py.iplot(data, filename='arson line graph')
